# Generated by Django 2.2.6 on 2019-10-17 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100)),
                ('s_phone', models.CharField(max_length=100)),
                ('s_mail', models.CharField(max_length=100)),
                ('s_registration', models.CharField(max_length=100)),
                ('d_admission_date', models.DateTimeField()),
                ('d_register_date', models.DateTimeField(auto_now_add=True)),
                ('b_in_charge', models.BooleanField(default=False)),
                ('r_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
