# Generated by Django 2.2 on 2019-10-29 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20191027_1400'),
        ('employee', '0002_employee_r_team'),
    ]

    operations = [
    ]
